dist: trusty
sudo: false
group: beta

language: node_js
node_js:
- lts/carbon
services:
- docker
cache:
  directories:
  - node_modules
before_install:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then BASE_NAME=${TRAVIS_BRANCH}; else BASE_NAME=pr${TRAVIS_PULL_REQUEST}; fi
- NAME=`echo ${BASE_NAME} | tr -cd '[\-._[:alnum:]]'`
- TS=`date +%Y%m%dT%H%M%S`
- VERSION_TAG=${NAME}-${TS}-${TRAVIS_COMMIT}
- TAGS="${NAME} ${VERSION_TAG}"
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ]; then TAGS="${TAGS} latest"; fi

- docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}

- "if [ -d node_modules ] && [ x$(cat node_modules/.last-node-version 2>/dev/null) != x$(node -e 'console.log(process.version)') ]; then npm rebuild && node -e 'console.log(process.version)' > node_modules/.last-node-version; fi"
install:
- npm install
- npm prune && npm shrinkwrap && mkdir -p deploy && cp package.json npm-shrinkwrap.json log4js.json deploy && cp -r src deploy/src && npm install --production --prefix deploy --ignore-scripts
after_success:
- docker build `echo ${TAGS} | sed -re "s,\b([-._[:alnum:]]+)\b,-t ${DOCKER_NAME}:\1,g"` .
deploy:
  provider: script
  script: "${SHELL} ./travis-deploy.sh ${DOCKER_NAME} ${TAGS}"
  on:
    all_branches: true
env:
  global:
    - DOCKER_NAME=collaborne/kubernetes-ingress-ca
    - secure: "Ir00b0+/Ur0NUEUiWZsOqxXr3jNMhjFQ2bwZ2SwAcxMrpu8bnMbWIQyn9LPNfBFf/Xa42rhcVcOcdLt90R5yrlxg7wkWqmR0Y6qh7PuAY8JKOiR3aER5gGNmkdPi5pWvIWn9KWwMjv4HqYGPiAQP37/K4UBMl7bikLDQzrEIqkRtF6Vneo+kKAc26kDur3mfIQFqSSE/e5GsOn5JIqs+gjvxCAcUfIGghEpm3TNdJ4bJKysetZEU6zDDmkmCk06Ouxf4rBeXjHAW/uyqBSJoXoQi1oDLdOPEpICcXMdz6GptmskgutBegBK1UH31A0HCCpIIhLE55HdFIQ+9004oLdNdJzDT2qM9rQU45noYYCS6DomwBGA+XMAqyPiPicNY5vfbFNLt2fvX3rDpJSm3CqcriVWzVjG0NjSSq8yVl2ZRFIB7CxZeGq2M5Qvm66e30MiA0Ayh8wzEBAFnY+t8EivsGiLq5ZZ4s2TmyyI/ZV74BZLLX8WqwAsCscaPVPcAfxl5pAKLLdn+aJD3XKNT27XV+AdBHZlVqCX0SCJy44BJdB3jDQ15x0MAQugRdpuMMX+dpwx2+trcf7m4Pfibwv9lbN8vLQ7pd4zg+hM29BYbxUNCogkS9m+PCm97zQZajJAD/jIumYheZ8v4bAVDKZLHIefQQ9liDSUXSkn9fvo="
    - secure: "FFfZs6pBNxJcyCyQ/B2DqZSDF8YMNsdUn58II08ASj4ynVOMm/sAwKUllDkxFIIDh5bY0wMkIDvQ/klupmAAK0DN2qJIZW9r1q3D8ER3QWcfzxTeriJ7iTfc+OGXVRxN5/yF0tfGDHtNujTsN/qrucE9rdf2u8R6Oi1+6fvKnKobSYMjrtUlQ9R30qYQFKZxPpkBUzS0w1xuaJGoUYWZyeBqzXh7sIcw4BAK3dYKvsQ0Q6VDiOXIhJagcsTWTE2Y/NzDdohUnG3r4AZgSV9PgPU1nrmQBPUGxo3cUfb0xv2NR7+QYkDNbGZ9Wb5d8YiKFF4rQfvAj1vxguKdizWHoJT9L0HNoVPbqxSkLR7sJx2yfk8B6RZJirwLCsf4RcVSfh8mW6DeSyPA1+cy6Pn3HFyRUUojmY0PEyZdFB98A9FZbvUrX64mmzkMAik3VgS3D91yYItmkl+1XEF4iZ+w29ucJUTvX7c4jAbJ1IcpZeV8lemyOcP7gfe8PUZCA1ww1FTYJ2RfXWw1p5E8oYAHPoeiYZbjk3Q70EKUs2PpKHOheyOq5begMQnIVVX2TIe75yZUA0zs1jGuuNv/1YL/gDQJOW34OowmDuntNd6PK6tzbK5qqHuvSoDxixrtTIpt6GWDLE3qvlulcwB1A1UhRoALkg2N5EU8o7lHtK4HgjA="



